# Generated by Django 6.0.6 on 2026-06-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='In acres', max_digits=6)),
                ('sowing_date', models.DateField()),
                ('fertilizer_used', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Growing', 'Growing'), ('Harvested', 'Harvested'), ('Diseased', 'Diseased')], max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmers.farmer')),
            ],
        ),
    ]
