# Generated by Django 6.0.6 on 2026-06-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='In kg', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price per kg', max_digits=10)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='crops.crop')),
            ],
        ),
    ]
